### ISSUE TITLE
Can't install module: Error: Could not install 'puppetlabs-concat' (v2.0.1)

### ISSUE THREAD

**Issue by daks** [jbussdieker/puppet-carbon#7]
Hi,

I'm using librarian-puppet to manage my Puppet modules. When I try to install module 'jbussdieker/carbon' version 0.0.12, I got this error message:

     Error: Could not install 'puppetlabs-concat' (v2.0.1)
     No releases matching '2.0.1' are available from https://forgeapi.puppetlabs.com

Which is normal because v2.0.1 of puppetlabs/concat has been erased from forge.

When I look at the code, it seems that the metadata.json only specifies a version >= 1.1.0.

I'm not sure the problem comes from this module or from librarian-puppet. If you have any idea before I post this bug to librarian-puppet.

**Comment by jbussdieker** [comment]
I submitted a fix recently https://github.com/rodjek/librarian-puppet/pull/311. Not sure if a new release of librarian-puppet has been cut.

**Comment by jbussdieker** [comment]
It looks like librarian-puppet 2.2.1 has been released with the fix.
