### ISSUE TITLE
default storage aggregation rules differs from project ones

### ISSUE THREAD

**Issue by daks** [jbussdieker/puppet-carbon#9]
Hello,

I see that by default your module configures some aggregation rules in the storage-aggregation.conf, but it seems that they differ from the ones from the Graphite project, is this wanted or a mistake?

The aggregation which differ is the 'min' one, the method is 'sum' for your module but it's 'min' for the graphite project. see https://github.com/graphite-project/carbon/blob/master/conf/storage-aggregation.conf.example

If it's not wanted, I can create a PR.

Thanks

**Comment by jbussdieker** [comment]
Nice find! Surely a copy/paste oversight. PR is welcome.
